//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string authtoken { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<System.DateTime> expiredon { get; set; }
    }
}
